use std::{marker::Tuple};

use crate::nes_instructions::addressing_mode::{AddressingMode, count_address_bytes};

#[derive(Copy, Clone)]
pub enum Codes {
    Brk = 0x00,
    Inx = 0xE8,
    Lda = 0xA9,
    Tax = 0xAA,
    Zpg = 0x05,
}

// (1) i8 == Byte count, (2) i8 == Cycles
pub static INSTRU_MAP: Vec<Tuple> = vec![
    (0x00, 7, AddressingMode::NoneAddressing),
    (0xea, 2, AddressingMode::NoneAddressing),
    (0x69, 2, AddressingMode::Immediate),
    (0x65, 3, AddressingMode::ZeroPage),
    (0x75, 4, AddressingMode::ZeroPage_X),
    (0x6d, 4, AddressingMode::Absolute),
    (0x7d, 4, AddressingMode::Absolute_X),
    (0x79, 4, AddressingMode::Absolute_Y),
    (0x61, 6, AddressingMode::Indirect_X),
    (0x71, 5, AddressingMode::Indirect_Y),

    (0xe9, 2, AddressingMode::Immediate),
    (0xe5, 3, AddressingMode::ZeroPage),
    (0xf5, 4, AddressingMode::ZeroPage_X),
    (0xed, 4, AddressingMode::Absolute),
    (0xfd, 4, AddressingMode::Absolute_X),
    (0xf9, 4, AddressingMode::Absolute_Y),
    (0xe1, 6, AddressingMode::Indirect_X),
    (0xf1, 5, AddressingMode::Indirect_Y),
    (0x29, 2, AddressingMode::Immediate),
    (0x25, 3, AddressingMode::ZeroPage),
    (0x35, 4, AddressingMode::ZeroPage_X),
    (0x2d, 4, AddressingMode::Absolute),
    (0x3d, 4, AddressingMode::Absolute_X),
    (0x39, 4, AddressingMode::Absolute_Y),
    (0x21, 6, AddressingMode::Indirect_X),
    (0x31, 5, AddressingMode::Indirect_Y),
    (0x49, 2, AddressingMode::Immediate),
    (0x45, 3, AddressingMode::ZeroPage),
    (0x55, 4, AddressingMode::ZeroPage_X),
    (0x4d, 4, AddressingMode::Absolute),
    (0x5d, 4, AddressingMode::Absolute_X),
    (0x59, 4, AddressingMode::Absolute_Y),
    (0x41, 6, AddressingMode::Indirect_X),
    (0x51, 5, AddressingMode::Indirect_Y),
    (0x09, 2, AddressingMode::Immediate),
    (0x05, 3, AddressingMode::ZeroPage),
    (0x15, 4, AddressingMode::ZeroPage_X),
    (0x0d, 4, AddressingMode::Absolute),
    (0x1d, 4, AddressingMode::Absolute_X),
    (0x19, 4, AddressingMode::Absolute_Y),
    (0x01, 6, AddressingMode::Indirect_X),
    (0x11, 5, AddressingMode::Indirect_Y),
    (0x0a, 2, AddressingMode::NoneAddressing),
    (0x06, 5, AddressingMode::ZeroPage),
    (0x16, 6, AddressingMode::ZeroPage_X),
    (0x0e, 6, AddressingMode::Absolute),
    (0x1e, 7, AddressingMode::Absolute_X),

    (0x4a, 2, AddressingMode::NoneAddressing),
    (0x46, 5, AddressingMode::ZeroPage),
    (0x56, 6, AddressingMode::ZeroPage_X),
    (0x4e, 6, AddressingMode::Absolute),
    (0x5e, 7, AddressingMode::Absolute_X),

    (0x2a, 2, AddressingMode::NoneAddressing),
    (0x26, 5, AddressingMode::ZeroPage),
    (0x36, 6, AddressingMode::ZeroPage_X),
    (0x2e, 6, AddressingMode::Absolute),
    (0x3e, 7, AddressingMode::Absolute_X),

    (0x6a, 2, AddressingMode::NoneAddressing),
    (0x66, 5, AddressingMode::ZeroPage),
    (0x76, 6, AddressingMode::ZeroPage_X),
    (0x6e, 6, AddressingMode::Absolute),
    (0x7e, 7, AddressingMode::Absolute_X),

    (0xe6, 5, AddressingMode::ZeroPage),
    (0xf6, 6, AddressingMode::ZeroPage_X),
    (0xee, 6, AddressingMode::Absolute),
    (0xfe, 7, AddressingMode::Absolute_X),

    (0xe8, 2, AddressingMode::NoneAddressing),
    (0xc8, 2, AddressingMode::NoneAddressing),

    (0xc6, 5, AddressingMode::ZeroPage),
    (0xd6, 6, AddressingMode::ZeroPage_X),
    (0xce, 6, AddressingMode::Absolute),
    (0xde, 7, AddressingMode::Absolute_X),

    (0xca, 2, AddressingMode::NoneAddressing),
    (0x88, 2, AddressingMode::NoneAddressing),

    (0xc9, 2, AddressingMode::Immediate),
    (0xc5, 3, AddressingMode::ZeroPage),
    (0xd5, 4, AddressingMode::ZeroPage_X),
    (0xcd, 4, AddressingMode::Absolute),
    (0xdd, 4, AddressingMode::Absolute_X),
    (0xd9, 4, AddressingMode::Absolute_Y),
    (0xc1, 6, AddressingMode::Indirect_X),
    (0xd1, 5, AddressingMode::Indirect_Y),

    (0xc0, 2, AddressingMode::Immediate),
    (0xc4, 3, AddressingMode::ZeroPage),
    (0xcc, 4, AddressingMode::Absolute),

    (0xe0, 2, AddressingMode::Immediate),
    (0xe4, 3, AddressingMode::ZeroPage),
    (0xec, 4, AddressingMode::Absolute),

    (0x4c, 3, AddressingMode::NoneAddressing),
    (0x6c, 5, AddressingMode::NoneAddressing),

    (0x20, 6, AddressingMode::NoneAddressing),
    (0x60, 6, AddressingMode::NoneAddressing),

    (0x40, 6, AddressingMode::NoneAddressing),

    (0xd0, 2, AddressingMode::NoneAddressing),
    (0x70, 2, AddressingMode::NoneAddressing),
    (0x50, 2, AddressingMode::NoneAddressing),
    (0x30, 2, AddressingMode::NoneAddressing),
    (0xf0, 2, AddressingMode::NoneAddressing),
    (0xb0, 2, AddressingMode::NoneAddressing),
    (0x90, 2, AddressingMode::NoneAddressing),
    (0x10, 2, AddressingMode::NoneAddressing),

    (0x24, 3, AddressingMode::ZeroPage),
    (0x2c, 4, AddressingMode::Absolute),
    (0xA9, 2, AddressingMode::Immediate),
    (0xA5, 3, AddressingMode::ZeroPage),
    (0xB5, 4, AddressingMode::ZeroPage_X),
    (0xAD, 4, AddressingMode::Absolute),
    (0xBD, 4, AddressingMode::Absolute_X),
    (0xB9, 4, AddressingMode::Absolute_Y),
    (0xa1, 6, AddressingMode::Indirect_X),
    (0xb1, 5, AddressingMode::Indirect_Y),
    (0xa2, 2, AddressingMode::Immediate),
    (0xa6 , 3, AddressingMode::ZeroPage),
    (0xb6 , 4, AddressingMode::ZeroPage_Y),
    (0xae , 4, AddressingMode::Absolute),
    (0xbe , 4, AddressingMode::Absolute_Y),
    (0xa0 , 2, AddressingMode::Immediate),
    (0xa4 , 3, AddressingMode::ZeroPage),
    (0xb4 , 4, AddressingMode::ZeroPage_X),
    (0xac , 4, AddressingMode::Absolute),
    (0xbc , 4, AddressingMode::Absolute_X),
    (0x85 , 3, AddressingMode::ZeroPage),
    (0x95 , 4, AddressingMode::ZeroPage_X),
    (0x8d , 4, AddressingMode::Absolute),
    (0x9d , 5, AddressingMode::Absolute_X),
    (0x99 , 5, AddressingMode::Absolute_Y),
    (0x81 , 6, AddressingMode::Indirect_X),
    (0x91 , 6, AddressingMode::Indirect_Y),
    (0x86 , 3, AddressingMode::ZeroPage),
    (0x96 , 4, AddressingMode::ZeroPage_Y),
    (0x8e , 4, AddressingMode::Absolute),
    (0x84 , 3, AddressingMode::ZeroPage),
    (0x94 , 4, AddressingMode::ZeroPage_X),
    (0x8c , 4, AddressingMode::Absolute),
    (0xD8 , 2, AddressingMode::NoneAddressing),
    (0x58 , 2, AddressingMode::NoneAddressing),
    (0xb8 , 2, AddressingMode::NoneAddressing),
    (0x18 , 2, AddressingMode::NoneAddressing),
    (0x38 , 2, AddressingMode::NoneAddressing),
    (0x78 , 2, AddressingMode::NoneAddressing),
    (0xf8 , 2, AddressingMode::NoneAddressing),
    (0xaa , 2, AddressingMode::NoneAddressing),
    (0xa8 , 2, AddressingMode::NoneAddressing),
    (0xba , 2, AddressingMode::NoneAddressing),
    (0x8a , 2, AddressingMode::NoneAddressing),
    (0x9a , 2, AddressingMode::NoneAddressing),
    (0x98 , 2, AddressingMode::NoneAddressing),
    (0x48 , 3, AddressingMode::NoneAddressing),
    (0x68 , 4, AddressingMode::NoneAddressing),
    (0x08 , 3, AddressingMode::NoneAddressing),
    (0x28 , 4, AddressingMode::NoneAddressing),
    (0xc7, 5, AddressingMode::ZeroPage),
    (0xd7, 6, AddressingMode::ZeroPage_X),
    (0xCF, 6, AddressingMode::Absolute),
    (0xdF, 7, AddressingMode::Absolute_X),
    (0xdb, 7, AddressingMode::Absolute_Y),
    (0xd3, 8, AddressingMode::Indirect_Y),
    (0xc3, 8, AddressingMode::Indirect_X),
    (0x27, 5, AddressingMode::ZeroPage),
    (0x37, 6, AddressingMode::ZeroPage_X),
    (0x2F, 6, AddressingMode::Absolute),
    (0x3F, 7, AddressingMode::Absolute_X),
    (0x3b, 7, AddressingMode::Absolute_Y),
    (0x33, 8, AddressingMode::Indirect_Y),
    (0x23, 8, AddressingMode::Indirect_X),
    (0x07, 5, AddressingMode::ZeroPage),
    (0x17, 6, AddressingMode::ZeroPage_X),
    (0x0F, 6, AddressingMode::Absolute),
    (0x1f, 7, AddressingMode::Absolute_X),
    (0x1b, 7, AddressingMode::Absolute_Y),
    (0x03, 8, AddressingMode::Indirect_X),
    (0x13, 8, AddressingMode::Indirect_Y),
    (0x47, 5, AddressingMode::ZeroPage),
    (0x57, 6, AddressingMode::ZeroPage_X),
    (0x4F, 6, AddressingMode::Absolute),
    (0x5f, 7, AddressingMode::Absolute_X),
    (0x5b, 7, AddressingMode::Absolute_Y),
    (0x43, 8, AddressingMode::Indirect_X),
    (0x53, 8, AddressingMode::Indirect_Y),
    (0x80,2, AddressingMode::Immediate),
    (0x82,2, AddressingMode::Immediate),
    (0x89,2, AddressingMode::Immediate),
    (0xc2,2, AddressingMode::Immediate),
    (0xe2,2, AddressingMode::Immediate),
    (0xCB,2, AddressingMode::Immediate),
    (0x6B,2, AddressingMode::Immediate),
    (0xeb,2, AddressingMode::Immediate),
    (0x0b,2, AddressingMode::Immediate),
    (0x2b,2, AddressingMode::Immediate),
    (0x4b,2, AddressingMode::Immediate),
    // (0xCB, IGN, 3,4, AddressingMode::Absolute_X),
    (0x04,3, AddressingMode::ZeroPage),
    (0x44,3, AddressingMode::ZeroPage),
    (0x64,3, AddressingMode::ZeroPage),
    (0x14, 4, AddressingMode::ZeroPage_X),
    (0x34, 4, AddressingMode::ZeroPage_X),
    (0x54, 4, AddressingMode::ZeroPage_X),
    (0x74, 4, AddressingMode::ZeroPage_X),
    (0xd4, 4, AddressingMode::ZeroPage_X),
    (0xf4, 4, AddressingMode::ZeroPage_X),
    (0x0c, 4, AddressingMode::Absolute),
    (0x1c, 4, AddressingMode::Absolute_X),
    (0x3c, 4 , AddressingMode::Absolute_X),
    (0x5c, 4 , AddressingMode::Absolute_X),
    (0x7c, 4 , AddressingMode::Absolute_X),
    (0xdc, 4, AddressingMode::Absolute_X),
    (0xfc, 4, AddressingMode::Absolute_X),
    (0x67, 5, AddressingMode::ZeroPage),
    (0x77, 6, AddressingMode::ZeroPage_X),
    (0x6f, 6, AddressingMode::Absolute),
    (0x7f, 7, AddressingMode::Absolute_X),
    (0x7b, 7, AddressingMode::Absolute_Y),
    (0x63, 8, AddressingMode::Indirect_X),
    (0x73, 8, AddressingMode::Indirect_Y),
    (0xe7,5, AddressingMode::ZeroPage),
    (0xf7,6, AddressingMode::ZeroPage_X),
    (0xef,6, AddressingMode::Absolute),
    (0xff,7, AddressingMode::Absolute_X),
    (0xfb,7, AddressingMode::Absolute_Y),
    (0xe3,8, AddressingMode::Indirect_X),
    (0xf3,8, AddressingMode::Indirect_Y),
    (0x02,2, AddressingMode::NoneAddressing),
    (0x12,2, AddressingMode::NoneAddressing),
    (0x22,2, AddressingMode::NoneAddressing),
    (0x32,2, AddressingMode::NoneAddressing),
    (0x42,2, AddressingMode::NoneAddressing),
    (0x52,2, AddressingMode::NoneAddressing),
    (0x62,2, AddressingMode::NoneAddressing),
    (0x72,2, AddressingMode::NoneAddressing),
    (0x92,2, AddressingMode::NoneAddressing),
    (0xb2,2, AddressingMode::NoneAddressing),
    (0xd2,2, AddressingMode::NoneAddressing),
    (0xf2,2, AddressingMode::NoneAddressing),

    (0x1a,2, AddressingMode::NoneAddressing),
    (0x3a,2, AddressingMode::NoneAddressing),
    (0x5a,2, AddressingMode::NoneAddressing),
    (0x7a,2, AddressingMode::NoneAddressing),
    (0xda,2, AddressingMode::NoneAddressing),
    // (0xEA1,2, AddressingMode::NoneAddressing),
    (0xfa,2, AddressingMode::NoneAddressing),

    (0xab, 3, AddressingMode::Immediate), //todo: highly unstable and not used
    //http://visual6502.org/wiki/index.php?title=6502_Opcode_8B_%28XAA,_ANE%29
    (0x8b, 3, AddressingMode::Immediate), //todo: highly unstable and not used
    (0xbb, 2, AddressingMode::Absolute_Y), //todo: highly unstable and not used
    (0x9b, 2, AddressingMode::Absolute_Y), //todo: highly unstable and not used
    (0x93, 8, AddressingMode::Indirect_Y), //todo: highly unstable and not used
    (0x9f, 4, AddressingMode::Absolute_Y), //todo: highly unstable and not used
    (0x9e, 4, AddressingMode::Absolute_Y), //todo: highly unstable and not used
    (0x9c, 4, AddressingMode::Absolute_X), //todo: highly unstable and not used

    (0xa7, 3, AddressingMode::ZeroPage),
    (0xb7, 4, AddressingMode::ZeroPage_Y),
    (0xaf, 4, AddressingMode::Absolute),
    (0xbf, 4, AddressingMode::Absolute_Y),
    (0xa3, 6, AddressingMode::Indirect_X),
    (0xb3, 5, AddressingMode::Indirect_Y),

    (0x87, 3, AddressingMode::ZeroPage),
    (0x97, 4, AddressingMode::ZeroPage_Y),
    (0x8f, 4, AddressingMode::Absolute),
    (0x83, 6, AddressingMode::Indirect_X),
];
